# Generated by Django 3.2.4 on 2021-06-20 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 2, 45, 45, 261136, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
