# Generated by Django 3.2.4 on 2021-09-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_rec', '0002_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='sub_class',
            new_name='subclass',
        ),
        migrations.AddField(
            model_name='results',
            name='class_subclass',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
